### ISSUE TITLE
Binary Request

### ISSUE THREAD

**Issue by marcussacana** [vn-tools/tlg2png#2]
Hi, i'm needing this program, but this source need of a "libpng" and this libpng need of zlib and xlib....
it's more fast if you compile for me, you can?

**Comment by rr-** [comment]
It's already available [here, right at releases...](https://github.com/vn-tools/tlg2png/releases).

If you for whatever reason want a static build, [here you go...](http://tmp.sakuya.pl/f/tlg2png.exe)

Anyway, have you considered using [arc_unpacker](https://github.com/vn-tools/arc_unpacker) which contains support for TLG (with bugfixes) and a lot more - all with nightly builds etc.?

**Comment by marcussacana** [comment]
i try before and don't works, but with a nightly build the arc_unpacker works, thanks man.
